### ISSUE TITLE
Summoning Gateway during a Auth prompt

### ISSUE THREAD

**Issue by FriendsNone** [vicr123/theshell#20]
Apperantly you can summon the Gateway while in a Auth prompt.

**Comment by Nevvulo** [comment]
Would this be considered a bug? I know that opening the Gateway doesn't really serve much functionality, as opening any apps will just result in the authentication prompt overlapping, but generally it doesn't seem catastrophic that you'd be able to do this. In most other operating systems, you can bypass the authentication dialog by tabbing away from it (this is possible in Windows by using `CTRL+ALT+DELETE`), so the fact that theShell allows you to open the Gateway almost seems intentional.

**Comment by vicr123** [comment]
Should be fixed in Blueprint :)
